# Generated by Django 4.0 on 2021-12-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.buildingdata')),
            ],
        ),
        migrations.CreateModel(
            name='HalfHourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField()),
                ('reading_date_time', models.DateTimeField()),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.meterdata')),
            ],
        ),
    ]
