# Generated by Django 4.0 on 2021-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='csv/'),
        ),
    ]
