# Generated by Django 4.0 on 2021-12-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('num_rating', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('avg_rating', models.FloatField()),
                ('num_pages', models.IntegerField()),
                ('original_publish_year', models.IntegerField()),
                ('award', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genres',
            field=models.TextField(max_length=500, verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
