# Generated by Django 4.0 on 2021-12-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_bookscomplete_delete_upload_alter_books_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
