# Generated by Django 4.0 on 2021-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_delete_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookscomplete',
            name='num_pages',
            field=models.CharField(max_length=50),
        ),
    ]
