# Generated by Django 4.0 on 2021-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_bookscomplete_num_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookscomplete',
            name='num_rating',
            field=models.CharField(max_length=50),
        ),
    ]
