# Generated by Django 4.0 on 2021-12-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_bookscomplete_num_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookscomplete',
            name='avg_rating',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookscomplete',
            name='num_reviews',
            field=models.CharField(max_length=50),
        ),
    ]
